name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          unzip -o Cinesuivi.zip
          ls -R | head -n 100
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build APK
        run: |
          GRADLE=$(find -name gradlew | head -n 1)
          chmod +x $GRADLE
          DIR=$(dirname $GRADL  cd $./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Cinesuivi-APK
          path: '**/build/outputs/apk/debug/*.apk'
